<?php

class model_showCart3 extends Model{
    function __construct()
    {
        parent::__construct();
    }

    function getbasketreview()
    {
        return parent::getbasket(); // TODO: Change the autogenerated stub
    }

    function postprice(){
        self::sessionInit();
        $addressinfo=self::sessionGet('addressinfo');
        $addressinfo=unserialize($addressinfo);
        $posttype=self::sessionGet('posttype');
        $cityid=$addressinfo['city'];

        $postPrice=$this->calculatepostprice($cityid);

        if($posttype==1){
            $postPrice=$postPrice['pishtaz'];
        }
        else if($posttype==2){
            $postPrice=$postPrice['sefareshi'];
        }

        return $postPrice;
    }

}

?>